# Generated by Django 5.2.1 on 2025-08-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_user_thread_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contenido',
            new_name='content',
        ),
    ]
